name: CI
on:
  push:
    branches:
      - master
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub Login
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin <<< "${{ secrets.DOCKERHUB_KEY }}"
      - name: Github Package Registry Login
        run: docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USER }} --password-stdin <<< "${{ secrets.TOKEN }}"
      - name: Build Docker Image - X86_64
        env:
            IMAGE_NAME: chrome-vpn
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:latest -f Dockerfile .
            docker push ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:latest